[package]
name = "actix_test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.115"
ml_library ={ path = "../ml_library"}
image = "0.25.1"
